spring.application.name=SocialBackEnd
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=${JWT_EXPIRATION}
application.security.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
cloudinary.secret_key=${CLOUDINARY_SECRET_KEY}