spring.application.name=SocialBackEnd
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=[IP_ADDRESS]
spring.datasource.username=[USERNAME]
spring.datasource.password=[PASSWORD]
application.security.jwt.secret-key=[SECRET_KEY]
application.security.jwt.expiration=[EXPIRATION]
application.security.cors.allowed-origins=[ALLOWED_ORIGINS]